"""add video studio tables

Revision ID: a9da80da9051
Revises: f42ad4074449
Create Date: 2026-07-03 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9da80da9051'
down_revision: Union[str, None] = 'c7b70d0f31b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(table_name: str) -> bool:
    return table_name in sa.inspect(op.get_bind()).get_table_names()


def _has_index(table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    if table_name not in inspector.get_table_names():
        return False
    return index_name in {index["name"] for index in inspector.get_indexes(table_name)}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table('video_projects'):
        op.create_table(
            'video_projects',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('fps', sa.Integer(), nullable=False),
            sa.Column('duration_seconds', sa.Float(), nullable=True),
            sa.Column('narration_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('narration_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('srt_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('chatterbox_config', sa.JSON(), nullable=True),
            sa.Column('youtube_config', sa.JSON(), nullable=True),
            sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('output_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('youtube_video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )
    if not _has_table('video_render_jobs'):
        op.create_table(
            'video_render_jobs',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('project_id', sa.Uuid(), nullable=False),
            sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('progress', sa.Integer(), nullable=False),
            sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('error', sa.JSON(), nullable=True),
            sa.Column('output_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('youtube_video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(
                ['project_id'], ['video_projects.id'], ondelete='CASCADE'
            ),
            sa.PrimaryKeyConstraint('id'),
        )
    if not _has_index('video_render_jobs', op.f('ix_video_render_jobs_project_id')):
        op.create_index(
            op.f('ix_video_render_jobs_project_id'),
            'video_render_jobs',
            ['project_id'],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_index('video_render_jobs', op.f('ix_video_render_jobs_project_id')):
        op.drop_index(
            op.f('ix_video_render_jobs_project_id'),
            table_name='video_render_jobs',
        )
    if _has_table('video_render_jobs'):
        op.drop_table('video_render_jobs')
    if _has_table('video_projects'):
        op.drop_table('video_projects')
    # ### end Alembic commands ###
